baseURL = 'https://13x13.ch/'
languageCode = 'de-ch'
title = '13×13 – Geschichten aus dem Wallis'
theme = 'ananke'

[params]
  description = 'Dreizehn Themen. Dreizehn Perspektiven. Jeden Monat neu.'
  author = 'Redaktion 13×13'
  featured_image = ''
  background_color_class = 'bg-near-white'
  recent_posts_number = 3

[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

[params.giscus]
  [params.giscus]
  repo = "bekuonen/13x13"
  repoid = "R_kgDORNugmg"
  category = "General"
  categoryid = "DIC_kwDORNugms4C2s5m"
